apiVersion: v1
kind: Service
metadata:
     name: my-svc
spec: 
   type: NodePort
   selector: 
     app: my-react-app
   ports: 
        - name: http
          nodePort: 30082
          port: 8080
          targetPort: 3000

